
/**

曲谱库

每首曲子包含：名称、难度、BPM、音符序列

音符格式：{ note: 'C4', duration: 1 } duration以拍为单位
*/

const Songs = [
{
id: 'twinkle',
name: '小星星',
emoji: '⭐',
difficulty: 1,
bpm: 80,
timeSignature: '4/4',
description: '最经典的入门曲目',
notes: [
{ note: 'C4', duration: 1 },
{ note: 'C4', duration: 1 },
{ note: 'G4', duration: 1 },
{ note: 'G4', duration: 1 },
{ note: 'A4', duration: 1 },
{ note: 'A4', duration: 1 },
{ note: 'G4', duration: 2 },
{ note: 'F4', duration: 1 },
{ note: 'F4', duration: 1 },
{ note: 'E4', duration: 1 },
{ note: 'E4', duration: 1 },
{ note: 'D4', duration: 1 },
{ note: 'D4', duration: 1 },
{ note: 'C4', duration: 2 },
]
},
{
id: 'mary-lamb',
name: '玛丽有只小羊羔',
emoji: '🐑',
difficulty: 1,
bpm: 90,
timeSignature: '4/4',
description: '简单又好听',
notes: [
{ note: 'E4', duration: 1 },
{ note: 'D4', duration: 1 },
{ note: 'C4', duration: 1 },
{ note: 'D4', duration: 1 },
{ note: 'E4', duration: 1 },
{ note: 'E4', duration: 1 },
{ note: 'E4', duration: 2 },
{ note: 'D4', duration: 1 },
{ note: 'D4', duration: 1 },
{ note: 'D4', duration: 2 },
{ note: 'E4', duration: 1 },
{ note: 'G4', duration: 1 },
{ note: 'G4', duration: 2 },
]
},
{
id: 'jingle-bells',
name: '铃儿响叮当',
emoji: '🔔',
difficulty: 2,
bpm: 100,
timeSignature: '4/4',
description: '欢快的节日歌曲',
notes: [
{ note: 'E4', duration: 1 },
{ note: 'E4', duration: 1 },
{ note: 'E4', duration: 2 },
{ note: 'E4', duration: 1 },
{ note: 'E4', duration: 1 },
{ note: 'E4', duration: 2 },
{ note: 'E4', duration: 1 },
{ note: 'G4', duration: 1 },
{ note: 'C4', duration: 1 },
{ note: 'D4', duration: 1 },
{ note: 'E4', duration: 4 },
{ note: 'F4', duration: 1 },
{ note: 'F4', duration: 1 },
{ note: 'F4', duration: 1 },
{ note: 'F4', duration: 1 },
{ note: 'F4', duration: 1 },
{ note: 'E4', duration: 1 },
{ note: 'E4', duration: 1 },
{ note: 'E4', duration: 1 },
{ note: 'E4', duration: 1 },
{ note: 'D4', duration: 1 },
{ note: 'D4', duration: 1 },
{ note: 'E4', duration: 1 },
{ note: 'D4', duration: 2 },
{ note: 'G4', duration: 2 },
]
},
{
id: 'ode-to-joy',
name: '欢乐颂',
emoji: '🎵',
difficulty: 2,
bpm: 85,
timeSignature: '4/4',
description: '贝多芬经典旋律',
notes: [
{ note: 'E4', duration: 1 },
{ note: 'E4', duration: 1 },
{ note: 'F4', duration: 1 },
{ note: 'G4', duration: 1 },
{ note: 'G4', duration: 1 },
{ note: 'F4', duration: 1 },
{ note: 'E4', duration: 1 },
{ note: 'D4', duration: 1 },
{ note: 'C4', duration: 1 },
{ note: 'C4', duration: 1 },
{ note: 'D4', duration: 1 },
{ note: 'E4', duration: 1 },
{ note: 'E4', duration: 1.5 },
{ note: 'D4', duration: 0.5 },
{ note: 'D4', duration: 2 },
]
},
{
id: 'happy-birthday',
name: '生日快乐',
emoji: '🎂',
difficulty: 2,
bpm: 90,
timeSignature: '3/4',
description: '送给朋友的祝福',
notes: [
{ note: 'C4', duration: 0.75 },
{ note: 'C4', duration: 0.25 },
{ note: 'D4', duration: 1 },
{ note: 'C4', duration: 1 },
{ note: 'F4', duration: 1 },
{ note: 'E4', duration: 2 },
{ note: 'C4', duration: 0.75 },
{ note: 'C4', duration: 0.25 },
{ note: 'D4', duration: 1 },
{ note: 'C4', duration: 1 },
{ note: 'G4', duration: 1 },
{ note: 'F4', duration: 2 },
]
},
{
id: 'little-tiger',
name: '两只老虎',
emoji: '🐯',
difficulty: 1,
bpm: 100,
timeSignature: '4/4',
description: '耳熟能详的儿歌',
notes: [
{ note: 'C4', duration: 1 },
{ note: 'D4', duration: 1 },
{ note: 'E4', duration: 1 },
{ note: 'C4', duration: 1 },
{ note: 'C4', duration: 1 },
{ note: 'D4', duration: 1 },
{ note: 'E4', duration: 1 },
{ note: 'C4', duration: 1 },
{ note: 'E4', duration: 1 },
{ note: 'F4', duration: 1 },
{ note: 'G4', duration: 2 },
{ note: 'E4', duration: 1 },
{ note: 'F4', duration: 1 },
{ note: 'G4', duration: 2 },
]
}
];